### ISSUE TITLE
Change project award API 

### ISSUE THREAD

**Issue by SaurabhChouhan** [ariprainfotech/nnxt#169]
Change

API name to '/:estimationID/project-awarded'

**Comment by kamleshgour** [comment]
Change project award API #169 ( This API  On-Hold for Page is designing)
This api name (API name to '/:estimationID/project-awarded') right or wrong 
because of more data are required..........
like 
Negotiated billed hours
Expected client release date
Expected start date of dev
Expected dev release date
Release version (name)
Manager of a release
Leader of a release
Planned employees for release
